name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Каждые 6 часов
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master  # Указываем явно ветку

      - name: Generate snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nikitaZeynalov
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Create output directory
        run: mkdir -p dist

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          commit_message: "Update snake animation [skip ci]"
          force: false
