name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nikitaZeynalov
          gif_out_path: assets/github-contribution-grid-snake.gif
          svg_out_path: assets/github-contribution-grid-snake.svg

      - name: Create assets directory
        run: mkdir -p assets

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/
          git commit -m "Update snake animation [skip ci]"
          git push
